language: node_js
node_js:
  - 6
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-webrtc' ]; then cd .. && eval "mv $currentfolder generator-webrtc" && cd generator-webrtc; fi

